### ISSUE TITLE
'Allowed Hosts' error when accessing docker deployed on personal VM

### ISSUE THREAD

**Issue by TathanT** [GSA/cpct-tool#1]
When deploying the docker image on a vm, you get the following error when you browse to the site:
`A server error occurred.  Please contact the administrator.`
Checking docker logs you see:
```bash
[tthacker@<hostname-here> cpct-tool]$ docker run -p 9005:8000 cpct-tool
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '<hostname-here>:9005'. You may need to add '<hostname-here>' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 149, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '<hostname-here>:9005'. You may need to add '<hostname-here>' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/whitenoise/middleware.py", line 59, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 104, in response_for_exception
    response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[10/Jan/2023 22:39:45] "GET / HTTP/1.1" 500 59
Invalid HTTP_HOST header: '<hostname-here>:9005'. You may need to add '<hostname-here>' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 149, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '<hostname-here>:9005'. You may need to add '<hostname-here>' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/whitenoise/middleware.py", line 59, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 104, in response_for_exception
    response = debug.technical_500_response(request, *sys.exc_info(), status_code=400)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 117, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 149, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 57, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 345, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by claytonjbarnette** [comment]
The **CPCT Tool** docker image uses port `8000` and your local private IP Address of `0.0.0.0` by default. This can be changed with adjustments made inside your Dockerfile to the `EXPOSE` and last `CMD` used to start **Django**. 

If you are running the `docker image` with different (custom) setting on the command line, your *Dockerfile* must match the adjusted setting you are using on the command line because of what *Django* expects when starting. The IP you are using will need to match what is used to start *Django* and be accessible to your pc.  This `IP` also needs to be added to the `ALLOWED_HOSTS` sections inside the `settings.py` file located in the `resources folder`. Then, *rebuild* the Docker image and run it with the adjusted settings to match the `IP` and `PORT` you are using.

You may have to make several adjustments depending on the many different settings that are allowed and the custom ones you are trying to use. More information can be found on the Docker website [here](https://docs.docker.com/engine/reference/commandline/run/).

Let me know if this helps. 

> **Tip:** Before making any adjustments to the Docker file, make a copy of the *original Dockerfile*. Rename the original to *Dockerfile.keep* or move it to a safe place. Then, make your adjustments to the copied version of the Dockerfile. Then rebuild the image and try rerunning the Docker image with the new setting.
